version: 2
jobs:
  build_and_test_jdk8:
    working_directory: ~/authmereloaded-jdk8
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
        MAVEN_OPTS: -Xmx2048m
    steps:
      - checkout
      - restore_cache:
          key: authmereloaded-{{ checksum "pom.xml" }}
     - run: mvn -T 2 dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: authmereloaded-{{ checksum "pom.xml" }}
      - run: mvn -T 2 package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/*.jar
  build_and_test_jdk9:
    working_directory: ~/authmereloaded-jdk9
    docker:
      - image: circleci/openjdk:9-jdk
    environment:
        MAVEN_OPTS: -Xmx2048m
    steps:
      - checkout
      - restore_cache:
          key: authmereloaded-{{ checksum "pom.xml" }}
     - run: mvn -T 2 dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: authmereloaded-{{ checksum "pom.xml" }}
      - run: mvn -T 2 package
      - store_test_results:
          path: target/surefire-reports
      - run: cp ./target/*.jar $CIRCLE_ARTIFACTS
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_jdk8
      - build_and_test_jdk9
